### ISSUE TITLE
hi omar, I'm trying to install this Geant4 version 

### ISSUE THREAD

**Issue by sophiemiddleton** [LDMXAnalysis/geant4#6]
https://github.com/LDMX-Software/geant4/blob/26aabffe112ed589afbbf9ed4e25f06d2649447a/CMakeLists.txt#L11

I see there's some merge issues in this CMake file, which is the current version of the file?

**Comment by omar-moreno** [comment]
Should be fixed now.

**Comment by sophiemiddleton** [comment]
great thanks
